sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - pip install coveralls
script: coverage run --source=appier_console setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: u6FRegAVUjWCT2m9gZlC4FqOgDvlDPz2Tl2FQqTXE9owd2nrvrXDh9LwQTQ8v5XyTrWotpw1Gp2JweoJHFcLOlXUNpzTy9xNRnalRAp9UjaDMtvDrjARRIsaKE4pI3NOtxWwpictyMlnVSgly1lku6Zu7g6aiexCNdcZ57SZcu7+xlaLgQvXZl14qGsJ71gSrZ0gKmRNLFod89Y1LgYOyTMX47kmHqX3GMsphEeTPGUQHVtFrBcEs6leZ0ygdyDTD1v1mpRhjLD9dKgRw8GLul6EpTvPZmOe6jZMsUWqSGgEz8dzZ2+OC96IpZlZlRPritJS9+jbjrUQfILXPXqkWNVGSkxAEEjj0b4tnukbsZWyoHD65jPbMybjKa2OrJLnto02ASLMLIhaIzdXXEzT+pFGoVd0x1TfLZvdrT4t7Yy9g9wNJTtmq1czXghxdYyQMzcN8H6B0rhj0qh/z/UXGQU6iVD5R4pVW62AcKRh/p1gA0Ipq52RM4w6R8mtUQou+SOj0e+MhzcZPP1jR7grIWu52AaacBIchBuSRNu0UK6lmz5rSLJsMwsXiDp1laIEjPMeSUe3Yd50z3pS+GLygteSItLN9QB/8oMDyZbMhmImcdBDthugtd16tqfUGueKnqP5t0sinVSgTNosjWkUzHJCPjGomVon96QKjhZLDc0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
